use crate::{exec, manifest, release};
use anyhow::{Context, Result};
use camino::{Utf8Path, Utf8PathBuf};
use serde::Serialize;
use std::fmt::Write as _;
use std::fs;

const GENERATED_WORKFLOW_HEADER: &str =
    "# Generated by `spctr ci sync --write`; edit spctr.toml instead.\n\n";

#[derive(Clone, Debug, Serialize)]
pub struct CiLanePlan {
    pub name: String,
    pub actions: Vec<exec::ExecPlan>,
}

#[derive(Clone, Debug, Serialize)]
pub struct CiPlan {
    pub project: String,
    pub slug: String,
    pub runner: Option<String>,
    pub lanes: Vec<CiLanePlan>,
}

#[derive(Clone, Debug, Serialize)]
pub struct GithubWorkflowJobPlan {
    pub id: String,
    pub condition: String,
    pub timeout_minutes: Option<u64>,
    pub requires: Vec<String>,
    pub actions: Vec<exec::ExecPlan>,
    pub runs_release_gate: bool,
}

#[derive(Clone, Debug, Serialize)]
pub struct GithubWorkflowPlan {
    pub name: String,
    pub slug: String,
    pub workflow_path: String,
    pub project_root: String,
    pub runner: String,
    pub path_filters: Vec<String>,
    pub python_version: Option<String>,
    pub has_pyproject: bool,
    pub cache_swiftpm_dependencies: bool,
    pub includes_pull_request: bool,
    pub includes_push_main: bool,
    pub includes_nightly: bool,
    pub nightly_cron: Option<String>,
    pub requires_nightly_schedule: bool,
    pub jobs: Vec<GithubWorkflowJobPlan>,
}

#[derive(Clone, Debug, Serialize)]
pub struct CiSyncEntry {
    pub project: Option<String>,
    pub workflow_path: String,
    pub status: String,
}

#[derive(Clone, Debug, Serialize)]
pub struct CiSyncReport {
    pub entries: Vec<CiSyncEntry>,
}

impl CiSyncReport {
    pub fn is_clean(&self) -> bool {
        self.entries.iter().all(|entry| entry.status == "in_sync")
    }

    pub fn drift_message(&self) -> String {
        self.entries
            .iter()
            .filter(|entry| entry.status != "in_sync")
            .map(|entry| format!("{}: {}", entry.workflow_path, entry.status))
            .collect::<Vec<_>>()
            .join("\n")
    }
}

pub fn plan(repo_root: &Utf8Path, project: Option<&str>) -> Result<CiPlan> {
    let manifest = lookup_ci_manifest(repo_root, project)?;
    plan_for_manifest(repo_root, &manifest)
}

pub fn github_plan(repo_root: &Utf8Path, project: Option<&str>) -> Result<GithubWorkflowPlan> {
    let manifest = lookup_ci_manifest(repo_root, project)?;
    let plan = plan_for_manifest(repo_root, &manifest)?;
    let nightly_cron = manifest
        .spctr
        .as_ref()
        .and_then(|spctr| spctr.ci.as_ref())
        .and_then(|ci| ci.nightly_cron.clone());
    let project_root = manifest
        .root
        .strip_prefix(repo_root)
        .with_context(|| {
            format!(
                "{}: project root {} is not inside repo root {}",
                manifest.path, manifest.root, repo_root
            )
        })?
        .to_owned();
    let python_version = detect_python_version(&manifest.root)?;
    let has_pyproject = manifest.root.join("pyproject.toml").is_file();
    let cache_swiftpm_dependencies = manifest.root.join("Package.swift").is_file()
        && manifest
            .spctr
            .as_ref()
            .and_then(|spctr| spctr.runtime.as_ref())
            .is_some_and(|runtime| runtime.cache_paths.iter().any(|path| path == ".build"));
    let workflow_path = format!(".github/workflows/{}-ci.yml", plan.slug);
    let path_filters = vec![format!("{project_root}/**")];
    let jobs = plan
        .lanes
        .iter()
        .filter(|lane| !lane.actions.is_empty())
        .map(|lane| GithubWorkflowJobPlan {
            id: lane.name.clone(),
            condition: lane_condition(&lane.name),
            timeout_minutes: lane_timeout_minutes(&lane.actions),
            requires: lane_requires(&lane.actions),
            actions: lane.actions.clone(),
            runs_release_gate: lane_runs_release_gate(&manifest, lane),
        })
        .collect::<Vec<_>>();

    Ok(GithubWorkflowPlan {
        name: format!("{}-ci", plan.slug),
        slug: plan.slug,
        workflow_path,
        project_root: project_root.to_string(),
        runner: plan.runner.unwrap_or_else(|| "ubuntu-latest".to_owned()),
        path_filters,
        python_version,
        has_pyproject,
        cache_swiftpm_dependencies,
        includes_pull_request: jobs.iter().any(|job| job.id == "pull_request"),
        includes_push_main: jobs.iter().any(|job| job.id == "push_main"),
        includes_nightly: jobs.iter().any(|job| job.id == "nightly"),
        nightly_cron: nightly_cron.clone(),
        requires_nightly_schedule: jobs.iter().any(|job| job.id == "nightly")
            && nightly_cron.is_none(),
        jobs,
    })
}

pub fn render_github_workflow(plan: &GithubWorkflowPlan) -> String {
    let mut yaml = String::new();
    writeln!(&mut yaml, "name: {}", plan.name).unwrap();
    yaml.push('\n');
    writeln!(&mut yaml, "on:").unwrap();
    if plan.includes_pull_request {
        writeln!(&mut yaml, "  pull_request:").unwrap();
        writeln!(&mut yaml, "    paths:").unwrap();
        for path in &plan.path_filters {
            writeln!(&mut yaml, "      - {}", yaml_quote(path)).unwrap();
        }
    }
    if plan.includes_push_main {
        writeln!(&mut yaml, "  push:").unwrap();
        writeln!(&mut yaml, "    branches: [main]").unwrap();
        writeln!(&mut yaml, "    paths:").unwrap();
        for path in &plan.path_filters {
            writeln!(&mut yaml, "      - {}", yaml_quote(path)).unwrap();
        }
    }
    writeln!(&mut yaml, "  workflow_dispatch:").unwrap();
    if let Some(cron) = &plan.nightly_cron {
        writeln!(&mut yaml, "  schedule:").unwrap();
        writeln!(&mut yaml, "    - cron: {}", yaml_quote(cron)).unwrap();
    } else if plan.requires_nightly_schedule {
        writeln!(
            &mut yaml,
            "  # Add a cron before checking in this workflow if you want the nightly lane to run automatically."
        )
        .unwrap();
        writeln!(&mut yaml, "  # schedule:").unwrap();
        writeln!(&mut yaml, "  #   - cron: {}", yaml_quote("0 8 * * 1")).unwrap();
    }

    yaml.push('\n');
    writeln!(&mut yaml, "concurrency:").unwrap();
    writeln!(
        &mut yaml,
        "  group: ${{{{ github.workflow }}}}-${{{{ github.ref }}}}"
    )
    .unwrap();
    writeln!(&mut yaml, "  cancel-in-progress: true").unwrap();

    yaml.push('\n');
    writeln!(&mut yaml, "permissions:").unwrap();
    writeln!(&mut yaml, "  contents: read").unwrap();

    yaml.push('\n');
    writeln!(&mut yaml, "jobs:").unwrap();
    for job in &plan.jobs {
        writeln!(&mut yaml, "  {}:", job.id).unwrap();
        writeln!(&mut yaml, "    if: {}", job.condition).unwrap();
        writeln!(&mut yaml, "    runs-on: {}", plan.runner).unwrap();
        if let Some(timeout_minutes) = job.timeout_minutes {
            writeln!(&mut yaml, "    timeout-minutes: {timeout_minutes}").unwrap();
        }
        writeln!(&mut yaml, "    steps:").unwrap();
        writeln!(&mut yaml, "      - uses: actions/checkout@v6.0.2").unwrap();
        render_setup_action(&mut yaml, plan, job);
        render_runtime_requirements(&mut yaml, job);
        render_swift_dependency_cache(&mut yaml, plan, job);
        for action in &job.actions {
            writeln!(&mut yaml, "      - name: Run exec {}", action.action).unwrap();
            writeln!(
                &mut yaml,
                "        run: {}",
                shell_command(&[
                    "./ops/spctr/target/release/spctr",
                    "exec",
                    "run",
                    "--project",
                    &plan.slug,
                    &action.action,
                ])
            )
            .unwrap();
        }
        if job.runs_release_gate {
            writeln!(&mut yaml, "      - name: Evaluate release gate").unwrap();
            writeln!(
                &mut yaml,
                "        run: {}",
                shell_command(&[
                    "./ops/spctr/target/release/spctr",
                    "release",
                    "gate",
                    &plan.slug,
                ])
            )
            .unwrap();
        }
    }
    yaml
}

pub fn sync(repo_root: &Utf8Path, project: Option<&str>, write: bool) -> Result<CiSyncReport> {
    let manifests = discover_ci_manifests(repo_root, project)?;
    let workflows = manifests
        .iter()
        .map(|manifest| {
            let workflow = github_plan(repo_root, Some(&manifest.slug))?;
            if workflow.includes_nightly && workflow.nightly_cron.is_none() {
                anyhow::bail!(
                    "{}: spctr.ci.nightly_cron is required for ci sync when nightly actions are declared",
                    manifest.path
                );
            }
            Ok((manifest.slug.clone(), workflow))
        })
        .collect::<Result<Vec<_>>>()?;

    let mut entries = Vec::new();
    for (slug, workflow) in &workflows {
        let content = managed_workflow_content(workflow);
        let workflow_path = repo_root.join(&workflow.workflow_path);
        let existing = fs::read_to_string(&workflow_path).ok();
        match existing.as_deref() {
            Some(current) if current == content => entries.push(CiSyncEntry {
                project: Some(slug.clone()),
                workflow_path: workflow.workflow_path.clone(),
                status: "in_sync".to_owned(),
            }),
            Some(current) if !current.starts_with(GENERATED_WORKFLOW_HEADER) => {
                anyhow::bail!(
                    "{}: refusing to overwrite unmanaged workflow; move it or adopt the generated path",
                    workflow.workflow_path
                );
            }
            Some(_) => {
                if write {
                    fs::write(&workflow_path, &content)
                        .with_context(|| format!("failed to write {}", workflow.workflow_path))?;
                }
                entries.push(CiSyncEntry {
                    project: Some(slug.clone()),
                    workflow_path: workflow.workflow_path.clone(),
                    status: if write {
                        "updated".to_owned()
                    } else {
                        "needs_update".to_owned()
                    },
                });
            }
            None => {
                if write {
                    if let Some(parent) = workflow_path.parent() {
                        fs::create_dir_all(parent)
                            .with_context(|| format!("failed to create {}", parent))?;
                    }
                    fs::write(&workflow_path, &content)
                        .with_context(|| format!("failed to write {}", workflow.workflow_path))?;
                }
                entries.push(CiSyncEntry {
                    project: Some(slug.clone()),
                    workflow_path: workflow.workflow_path.clone(),
                    status: if write {
                        "created".to_owned()
                    } else {
                        "needs_create".to_owned()
                    },
                });
            }
        }
    }

    if project.is_none() {
        let desired_paths = workflows
            .iter()
            .map(|(_, workflow)| workflow.workflow_path.clone())
            .collect::<Vec<_>>();
        for stale_path in discover_stale_generated_workflows(repo_root, &desired_paths)? {
            let abs_path = repo_root.join(&stale_path);
            if write {
                fs::remove_file(&abs_path)
                    .with_context(|| format!("failed to remove stale workflow {stale_path}"))?;
            }
            entries.push(CiSyncEntry {
                project: None,
                workflow_path: stale_path,
                status: if write {
                    "removed".to_owned()
                } else {
                    "needs_delete".to_owned()
                },
            });
        }
    }

    entries.sort_by(|left, right| left.workflow_path.cmp(&right.workflow_path));
    Ok(CiSyncReport { entries })
}

fn plan_for_manifest(
    repo_root: &Utf8Path,
    manifest: &crate::manifest::ProjectManifest,
) -> Result<CiPlan> {
    let spctr = manifest
        .spctr
        .as_ref()
        .with_context(|| format!("{}: project has no [spctr] section", manifest.path))?;
    let ci = spctr
        .ci
        .as_ref()
        .with_context(|| format!("{}: project has no [spctr.ci] section", manifest.path))?;
    Ok(CiPlan {
        project: manifest.title.clone(),
        slug: manifest.slug.clone(),
        runner: ci.runner.clone(),
        lanes: vec![
            build_lane(repo_root, manifest, "pull_request", &ci.pull_request)?,
            build_lane(repo_root, manifest, "push_main", &ci.push_main)?,
            build_lane(repo_root, manifest, "nightly", &ci.nightly)?,
        ],
    })
}

fn lookup_ci_manifest(
    repo_root: &Utf8Path,
    project: Option<&str>,
) -> Result<crate::manifest::ProjectManifest> {
    match project {
        Some(slug) => crate::release::lookup_project(repo_root, slug),
        None => manifest::discover_manifest(None),
    }
}

fn discover_ci_manifests(
    repo_root: &Utf8Path,
    project: Option<&str>,
) -> Result<Vec<crate::manifest::ProjectManifest>> {
    match project {
        Some(_) => {
            let manifest = lookup_ci_manifest(repo_root, project)?;
            if manifest
                .spctr
                .as_ref()
                .and_then(|spctr| spctr.ci.as_ref())
                .is_none()
            {
                anyhow::bail!("{}: project has no [spctr.ci] section", manifest.path);
            }
            Ok(vec![manifest])
        }
        None => {
            let mut manifests = Vec::new();
            for kind in ["dossiers", "addenda"] {
                let root = repo_root.join(kind);
                if !root.is_dir() {
                    continue;
                }
                let mut entries = Vec::new();
                for entry in
                    fs::read_dir(&root).with_context(|| format!("failed to read {root}"))?
                {
                    let entry = entry.with_context(|| format!("failed to read entry in {root}"))?;
                    let manifest_path: Utf8PathBuf = entry
                        .path()
                        .join("spctr.toml")
                        .try_into()
                        .context("non-UTF-8 path in ci manifest discovery")?;
                    if manifest_path.is_file() {
                        entries.push(manifest_path);
                    }
                }
                entries.sort();
                for manifest_path in entries {
                    let manifest = manifest::load_project_manifest(&manifest_path, None)?;
                    if manifest
                        .spctr
                        .as_ref()
                        .and_then(|spctr| spctr.ci.as_ref())
                        .is_some()
                    {
                        manifests.push(manifest);
                    }
                }
            }
            Ok(manifests)
        }
    }
}

fn discover_stale_generated_workflows(
    repo_root: &Utf8Path,
    desired_paths: &[String],
) -> Result<Vec<String>> {
    let workflows_root = repo_root.join(".github/workflows");
    if !workflows_root.is_dir() {
        return Ok(Vec::new());
    }
    let mut stale = Vec::new();
    for entry in fs::read_dir(&workflows_root)
        .with_context(|| format!("failed to read {}", workflows_root))?
    {
        let entry = entry.with_context(|| format!("failed to read entry in {}", workflows_root))?;
        let path: Utf8PathBuf = entry
            .path()
            .try_into()
            .context("non-UTF-8 path in workflow discovery")?;
        if path.extension() != Some("yml") {
            continue;
        }
        let rel_path = path
            .strip_prefix(repo_root)
            .with_context(|| {
                format!(
                    "workflow path {} is not inside repo root {}",
                    path, repo_root
                )
            })?
            .to_owned();
        if desired_paths
            .iter()
            .any(|desired| desired == rel_path.as_str())
        {
            continue;
        }
        let content = fs::read_to_string(&path)
            .with_context(|| format!("failed to read workflow {}", path))?;
        if content.starts_with(GENERATED_WORKFLOW_HEADER) {
            stale.push(rel_path.to_string());
        }
    }
    stale.sort();
    Ok(stale)
}

fn lane_condition(name: &str) -> String {
    match name {
        "pull_request" => {
            "${{ github.event_name == 'pull_request' || github.event_name == 'workflow_dispatch' }}"
                .to_owned()
        }
        "push_main" => "${{ (github.event_name == 'push' && github.ref == 'refs/heads/main') || github.event_name == 'workflow_dispatch' }}".to_owned(),
        "nightly" => {
            "${{ github.event_name == 'schedule' || github.event_name == 'workflow_dispatch' }}"
                .to_owned()
        }
        other => format!("${{{{ github.event_name == {} }}}}", yaml_quote(other)),
    }
}

fn build_lane(
    repo_root: &Utf8Path,
    manifest: &crate::manifest::ProjectManifest,
    name: &str,
    actions: &[String],
) -> Result<CiLanePlan> {
    Ok(CiLanePlan {
        name: name.to_owned(),
        actions: actions
            .iter()
            .map(|action| exec::build_plan(repo_root, manifest, action))
            .collect::<Result<Vec<_>>>()?,
    })
}

fn lane_runs_release_gate(manifest: &crate::manifest::ProjectManifest, lane: &CiLanePlan) -> bool {
    if manifest.release.stage != manifest::ReleaseStage::Promoted {
        return false;
    }
    release::required_exec_gate_actions(manifest)
        .iter()
        .all(|required| {
            lane.actions
                .iter()
                .any(|action| action.action.as_str() == *required)
        })
}

fn lane_timeout_minutes(actions: &[exec::ExecPlan]) -> Option<u64> {
    let timeout_sec = actions
        .iter()
        .map(|action| action.timeout_sec)
        .collect::<Option<Vec<_>>>()?
        .into_iter()
        .sum::<u64>();
    Some(timeout_sec.div_ceil(60).max(5))
}

fn lane_requires(actions: &[exec::ExecPlan]) -> Vec<String> {
    let mut requires = Vec::new();
    for action in actions {
        for requirement in &action.requires {
            if !requires.iter().any(|existing| existing == requirement) {
                requires.push(requirement.clone());
            }
        }
    }
    requires
}

fn detect_python_version(project_root: &Utf8Path) -> Result<Option<String>> {
    let pyproject_path = project_root.join("pyproject.toml");
    if !pyproject_path.is_file() {
        return Ok(None);
    }
    let content = fs::read_to_string(&pyproject_path)
        .with_context(|| format!("failed to read {}", pyproject_path))?;
    let value: toml::Value =
        toml::from_str(&content).with_context(|| format!("failed to parse {}", pyproject_path))?;
    if let Some(version) = value
        .get("tool")
        .and_then(|tool| tool.get("ty"))
        .and_then(|ty| ty.get("environment"))
        .and_then(|environment| environment.get("python-version"))
        .and_then(toml::Value::as_str)
        .map(str::trim)
        .filter(|version| !version.is_empty())
    {
        return Ok(Some(version.to_owned()));
    }
    if let Some(requires_python) = value
        .get("project")
        .and_then(|project| project.get("requires-python"))
        .and_then(toml::Value::as_str)
    {
        for token in requires_python.split(|ch: char| !ch.is_ascii_alphanumeric() && ch != '.') {
            if token.chars().next().is_some_and(|ch| ch.is_ascii_digit()) {
                let mut parts = token.split('.');
                if let (Some(major), Some(minor)) = (parts.next(), parts.next()) {
                    return Ok(Some(format!("{major}.{minor}")));
                }
            }
        }
    }
    Ok(None)
}

fn render_setup_action(yaml: &mut String, plan: &GithubWorkflowPlan, job: &GithubWorkflowJobPlan) {
    writeln!(yaml, "      - name: Setup spctr project").unwrap();
    writeln!(yaml, "        uses: ./.github/actions/setup-spctr").unwrap();
    writeln!(yaml, "        with:").unwrap();
    writeln!(
        yaml,
        "          project-root: {}",
        yaml_quote(&plan.project_root)
    )
    .unwrap();
    writeln!(
        yaml,
        "          use-python: {}",
        yaml_quote(if job_requires_python(job) {
            "true"
        } else {
            "false"
        })
    )
    .unwrap();
    if let Some(version) = &plan.python_version {
        writeln!(yaml, "          python-version: {}", yaml_quote(version)).unwrap();
    }
    writeln!(
        yaml,
        "          use-uv: {}",
        yaml_quote(if job_requires_uv(job) {
            "true"
        } else {
            "false"
        })
    )
    .unwrap();
    writeln!(
        yaml,
        "          sync-python: {}",
        yaml_quote(if job_requires_uv(job) && plan.has_pyproject {
            "true"
        } else {
            "false"
        })
    )
    .unwrap();
    if job_requires_lean(job) {
        writeln!(yaml, "          use-lean: 'true'").unwrap();
    }
    let rust_targets = rust_toolchain_targets(job);
    if !rust_targets.is_empty() {
        writeln!(
            yaml,
            "          rust-targets: {}",
            yaml_quote(&rust_targets.join(","))
        )
        .unwrap();
    }
}

fn render_runtime_requirements(yaml: &mut String, job: &GithubWorkflowJobPlan) {
    let unsupported = unsupported_requires(job);
    if unsupported.is_empty() {
        return;
    }

    writeln!(yaml, "      - name: Verify declared runtime requirements").unwrap();
    writeln!(yaml, "        run: |").unwrap();
    writeln!(yaml, "          set -euo pipefail").unwrap();
    for requirement in unsupported {
        for line in requirement_check_lines(requirement) {
            writeln!(yaml, "          {line}").unwrap();
        }
    }
}

fn render_swift_dependency_cache(
    yaml: &mut String,
    plan: &GithubWorkflowPlan,
    job: &GithubWorkflowJobPlan,
) {
    if !plan.cache_swiftpm_dependencies || !job_requires_swift(job) {
        return;
    }

    let project_path = |path: &str| Utf8Path::new(&plan.project_root).join(path).to_string();
    writeln!(yaml, "      - name: Cache SwiftPM dependencies").unwrap();
    writeln!(yaml, "        uses: actions/cache@v5.0.5").unwrap();
    writeln!(yaml, "        with:").unwrap();
    writeln!(yaml, "          path: |").unwrap();
    for path in [
        ".build/artifacts",
        ".build/checkouts",
        ".build/repositories",
    ] {
        writeln!(yaml, "            {}", project_path(path)).unwrap();
    }
    let key_inputs = ["Package.swift", "Package.resolved"]
        .into_iter()
        .map(project_path)
        .map(|path| yaml_quote(&path))
        .collect::<Vec<_>>()
        .join(", ");
    writeln!(
        yaml,
        "          key: spctr-swiftpm-deps-v1-${{{{ runner.os }}}}-${{{{ runner.arch }}}}-{}-${{{{ hashFiles({key_inputs}) }}}}-{}",
        plan.slug, job.id
    )
    .unwrap();
    writeln!(yaml, "          restore-keys: |").unwrap();
    writeln!(
        yaml,
        "            spctr-swiftpm-deps-v1-${{{{ runner.os }}}}-${{{{ runner.arch }}}}-{}-${{{{ hashFiles({key_inputs}) }}}}-",
        plan.slug
    )
    .unwrap();
}

fn job_requires_python(job: &GithubWorkflowJobPlan) -> bool {
    job.requires
        .iter()
        .any(|requirement| matches!(requirement.as_str(), "python" | "uv"))
}

fn job_requires_uv(job: &GithubWorkflowJobPlan) -> bool {
    job.requires.iter().any(|requirement| requirement == "uv")
}

fn job_requires_swift(job: &GithubWorkflowJobPlan) -> bool {
    job.requires
        .iter()
        .any(|requirement| requirement == "swift")
}

fn job_requires_lean(job: &GithubWorkflowJobPlan) -> bool {
    job.requires.iter().any(|requirement| requirement == "lean")
}

fn rust_toolchain_targets(job: &GithubWorkflowJobPlan) -> Vec<&str> {
    let mut targets = Vec::new();
    for requirement in &job.requires {
        if requirement == "wasm32-unknown-unknown" && !targets.contains(&"wasm32-unknown-unknown") {
            targets.push("wasm32-unknown-unknown");
        }
    }
    targets
}

fn unsupported_requires(job: &GithubWorkflowJobPlan) -> Vec<&str> {
    job.requires
        .iter()
        .map(String::as_str)
        .filter(|requirement| {
            !matches!(
                *requirement,
                "python" | "uv" | "rust" | "lean" | "wasm32-unknown-unknown"
            )
        })
        .collect()
}

fn requirement_check_lines(requirement: &str) -> Vec<String> {
    match requirement {
        "python" => vec![
            "if ! command -v python3 >/dev/null && ! command -v python >/dev/null; then".to_owned(),
            "  echo \"missing required runtime: python\" >&2".to_owned(),
            "  exit 1".to_owned(),
            "fi".to_owned(),
        ],
        "rust" => vec![
            "if ! command -v cargo >/dev/null; then".to_owned(),
            "  echo \"missing required runtime: rust\" >&2".to_owned(),
            "  exit 1".to_owned(),
            "fi".to_owned(),
        ],
        other => vec![
            format!("if ! command -v {} >/dev/null; then", shell_quote(other)),
            format!("  echo \"missing required runtime: {other}\" >&2"),
            "  exit 1".to_owned(),
            "fi".to_owned(),
        ],
    }
}

fn shell_command(args: &[&str]) -> String {
    args.iter()
        .map(|arg| shell_quote(arg))
        .collect::<Vec<_>>()
        .join(" ")
}

fn shell_quote(arg: &str) -> String {
    if arg.bytes().all(|byte| {
        byte.is_ascii_alphanumeric() || matches!(byte, b'-' | b'_' | b'.' | b'/' | b':')
    }) {
        arg.to_owned()
    } else {
        format!("'{}'", arg.replace('\'', "'\"'\"'"))
    }
}

fn yaml_quote(value: &str) -> String {
    format!("'{}'", value.replace('\'', "''"))
}

fn managed_workflow_content(plan: &GithubWorkflowPlan) -> String {
    format!(
        "{GENERATED_WORKFLOW_HEADER}{}",
        render_github_workflow(plan)
    )
}
