// Compile from the repository root with typst compile --root . --font-path addenda/typst-field-manual/assets/fonts site/style-study/publications/image.typ site/style-study/publications/image.pdf
#import "../../../addenda/typst-field-manual/tokens.typ": tokens
#let publication(kind: "image") = {
  set document(title: "How much does shape explain? — Publication study", author: "Specter Labs")
  set page(paper: "a4", margin: 22mm, fill: rgb("f8f4ea"))
  set text(font: tokens.fonts.body, size: 11pt, fill: rgb("20212b"))
  if kind == "cover" {
    set page(fill: rgb("ad7b37"))
    set text(fill: white)
    text(font: tokens.fonts.display, stretch: 75%, weight: "bold", size: 66pt)[How much\ does shape\ explain?]
    v(12mm)
    text(size: 15pt)[Flow Lenia, simulated tissue, and fish]
    v(1fr)
    image("../../assets/logo-black.svg", width: 14mm)
    v(6mm)
    text(font: tokens.fonts.mono, size: 10pt)[SPECTER LABS / PUBLICATION STUDY]
  } else if kind == "journal" {
    text(size: 40pt, style: "italic")[Studies in form]
    v(5mm)
    text(font: tokens.fonts.mono, size: 9pt)[SPECTER LABS / JOURNAL FORMAT STUDY]
    v(26mm)
    text(size: 27pt)[Contents]
    v(13mm)
    grid(columns: (1fr, auto), column-gutter: 8mm, row-gutter: 10mm,
      [How much does shape explain?\ #text(size: 10pt)[Comparing shapes across three systems]], [02],
      [Comparison plate\ #text(size: 10pt)[Twelve measurements and their differences]], [03],
      [Figure sources\ #text(size: 10pt)[Data and the published fish landmark study]], [04])
    v(1fr)
    text(size: 10pt)[A prototype issue built around one investigation. The following pages show the article opening, figure plate, and sources.]
  } else {
    align(center, text(size: 13pt, style: "italic")[How much does shape explain?])
    v(14mm)
    align(center, image("../../assets/blog/lenia-morphospace-report/motion/870da94a.png", width: 135mm))
    v(5mm)
    text(size: 10pt)[Flow Lenia specimen 870da94a. Native body rendering from a 256 × 256 simulation grid. This specimen belongs to the separate obstacle experiment, not the fish-near group.]
    v(1fr)
    text(font: tokens.fonts.mono, size: 9pt)[SPECTER LABS / IMAGE-LED OPENING STUDY]
  }
  pagebreak()
  set page(fill: rgb("f8f4ea"), footer: context align(right, text(font: tokens.fonts.mono, size: 8pt)[Publication prototype · #counter(page).display()]))
  set text(fill: rgb("20212b"), size: 11pt)
  text(font: tokens.fonts.display, stretch: 75%, size: 34pt, weight: "bold")[How much does shape explain?]
  v(5mm)
  text(size: 16pt, style: "italic")[Comparing Flow Lenia, simulated tissue, and fish]
  v(12mm)
  grid(columns: (1fr, 1fr), column-gutter: 8mm, [
    We measured the shapes of 25,167 patterns generated by Flow Lenia, then compared them with measurements of real fish. A group chosen before looking at the fish data had unexpectedly similar proportions.

    The comparison uses twelve normalized measurements. The selected group contains 256 observations. Its median distance to the nearest fish is 3.30, compared with 5.90 across the full Lenia sample.

  ], [
    These are distances in a space of measurements. They do not mean that the simulated patterns have fish anatomy, or that the same process produced them. The next question is whether similar shapes respond similarly when disturbed.

    The report follows that question from the shape map to a separate experiment with moving bodies and obstacles.
  ])
  v(6mm)
  text(size: 34pt, fill: rgb("344aa0"))[5.90 → 3.30]
  parbreak()
  text(size: 10pt)[Median distance to the nearest fish: full sample → selected group.]
  v(6mm)
  image("../../assets/blog/lenia-morphospace-report/fig-measured-map.svg", width: 100%, height: 43mm, fit: "contain")
  v(6mm)
  link("https://specterlab.org/dossiers/lenia-swarm/morphospace/")[Full investigation and data]
  v(1fr)
  text(size: 9pt)[Layout study, September 2026. This excerpt is a publication prototype, not the complete research article.]
  pagebreak()
  text(size: 24pt)[Comparison plate]
  v(8mm)
  image("../assets/comparison-plate.svg", width: 100%)
  pagebreak()
  text(size: 28pt)[Figure sources]
  v(12mm)
  [The comparison plate is generated from the report’s published fish-explainer.json. Each row compares one Lenia pattern, flow-map-elite-53, with its nearest fish and simulated-tissue neighbors. All twelve coordinate differences share one scale.]
  v(8mm)
  [The cover specimen, when shown, comes from the separate obstacle experiment. It is not evidence for the fish-near comparison.]
  v(8mm)
  link("https://doi.org/10.1038/s41598-023-48086-5")[Fish landmark study · Scientific Reports]
  v(8mm)
  link("https://www.are.na/phil-rohr/specter-eehguc2mfdg")[Visual references · Phil Rohr’s Are.na collection]
  v(8mm)
  [Format references: image-led editorial pages, Synergetics of Cognition, and the Bell System Technical Journal. Historical references inform composition and typography; the figures in this prototype come from the research.]
}
